LOCKFILE_VERSION = "1.0.0"
LOCKFILE = "nuclear.lock"

def parse_lockfile() -> dict:
    packages = {}
    try:
        with open(LOCKFILE) as f:
            contents = f.readlines()
    except OSError:
        return packages
    for line in contents:
        line = line.strip()
        if line.startswith("#") or not line:
            continue
        parts = line.split()
        if len(parts) != 4:
            continue
        packages[parts[0]] = [*parts]
    return packages

def save(user: str, repo: str, version: str, url: str, sha256: str) -> None:
    """
    Save package information into a lockfile
    """
    package_name = f"{user}/{repo}"
    packages = parse_lockfile()
    packages[package_name] = [package_name, version, url, sha256] # add/overwrite a package
    with open(LOCKFILE,"w") as f:
        f.write("### DO NOT EDIT: THIS IS AN AUTOGENERATED FILE ###\n")
        f.write(f"### {LOCKFILE} version {LOCKFILE_VERSION} ###\n\n")
        for package_data in packages.values():
            f.write(f"{' '.join(package_data)}\n")
