LOCKFILE_VERSION = "1.0.0"

def save(user, repo, version, url, sha256):
    """
    Save package information into a lockfile
    """
    package_name = f"{user}/{repo}"

    with open("nuclear.lock","w") as f:
        f.write("### DO NOT EDIT: THIS IS AN AUTOGENERATED FILE ###\n")
        f.write(f"### nuclear.lock version {LOCKFILE_VERSION} ###\n\n")
        f.write(f"{package_name} {version} {url} {sha256}")
